export const deviceHTML = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connect Hopsesh</title><link rel="stylesheet" href="/device.css"><main><h1>Connect a machine</h1><p>Enter the code displayed by Hopsesh on the machine you are connecting.</p><form id="code"><label for="userCode">Machine code</label><input id="userCode" autocomplete="off" autocapitalize="characters" maxlength="11" pattern="[A-Fa-f0-9]{5}-[A-Fa-f0-9]{5}" required placeholder="123AB-456CD"><button>Review machine</button></form><section id="review" hidden><h2>Check this machine</h2><p>Compare the code and full fingerprint with Hopsesh before approving.</p><dl><dt>Code</dt><dd id="confirmCode"></dd><dt>Machine</dt><dd id="endpoint"></dd><dt>Fingerprint</dt><dd id="fingerprint"></dd></dl><p>This allows encrypted relay delivery for 24 hours. Conversation sharing and receiving need separate approval in Hopsesh.</p><button id="approve">Allow delivery</button><button id="deny">Deny</button></section><p id="status" role="status" aria-live="polite"></p></main><script type="module" src="/device.js"></script></html>`;
export const deviceCSS = `:root{color-scheme:light dark;font:17px system-ui}body{margin:0}main{max-width:36rem;margin:8vh auto;padding:1.5rem}label,dt{display:block;font-weight:600}input,button{font:inherit;padding:.65rem;margin:.5rem .4rem .5rem 0}input{display:block;width:12rem}dd{margin:.25rem 0 1rem;overflow-wrap:anywhere}button:disabled{opacity:.6}#status{min-height:2rem}`;
export const deviceJS = `let review=null;const el=id=>document.getElementById(id);const initial=new URLSearchParams(location.search).get('user_code');if(/^[A-F0-9]{5}-[A-F0-9]{5}$/.test(initial||''))el('userCode').value=initial;async function call(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Hopsesh-CSRF':'review'},body:new URLSearchParams(body),redirect:'error'});const data=await r.json();if(!r.ok)throw new Error(data.error==='invalid_grant'?'This code is expired or already used. Start again from Hopsesh.':'Could not approve this request. Check the code and try again.');return data}function busy(value){document.querySelectorAll('button,input').forEach(e=>e.disabled=value)}el('code').addEventListener('submit',async e=>{e.preventDefault();busy(true);el('status').textContent='Checking the code…';try{review=await call('/v1/device/review',{user_code:el('userCode').value.trim().toUpperCase()});el('confirmCode').textContent=review.user_code;el('endpoint').textContent=review.endpoint;el('fingerprint').textContent=review.device;el('review').hidden=false;el('status').textContent='Compare these details with the requesting machine.'}catch(err){el('status').textContent=err.message}finally{busy(false)}});for(const decision of ['approve','deny'])el(decision).addEventListener('click',async()=>{if(!review)return;busy(true);try{const result=await call('/v1/device/approve',{user_code:review.user_code,nonce:review.nonce,decision});review=null;if(result.redirect_uri){location.assign(result.redirect_uri);return;}el('review').hidden=true;el('status').textContent=decision==='approve'?'Approved. Return to Hopsesh on that machine.':'Denied. No delivery access was granted.'}catch(err){el('status').textContent=err.message}finally{busy(false)}});`;
export function deviceAsset(path) {
 const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; form-action 'none'; frame-ancestors 'none'; base-uri 'none'"};
 if(path==='/device')return new Response(deviceHTML,{headers:{...headers,'Content-Type':'text/html; charset=utf-8'}});
 if(path==='/device.js')return new Response(deviceJS,{headers:{...headers,'Content-Type':'text/javascript; charset=utf-8'}});
 if(path==='/device.css')return new Response(deviceCSS,{headers:{...headers,'Content-Type':'text/css; charset=utf-8'}});
 return null;
}
